/**
 * Equipment: the mixing/forming/dosing, cooling/finishing/decoration, and
 * packaging/quality-control machine families. Every named machine here is
 * built on `plant/unit.ts`'s shared balance guarantee and driven by
 * `process/machine.ts`'s `Machine` — modes, setpoints, interlocks and wear
 * like any other machine in this simulation. See each file's own doc
 * comment for the physical shapes its named machines share.
 */

export type { MassShare, WashDownParams, WashDownResult } from './shared.js';
export {
  AIR_DENSITY_KG_PER_M3,
  CARBON_DIOXIDE_DENSITY_KG_PER_M3,
  NITROGEN_DENSITY_KG_PER_M3,
  UNIFORM_PROFILE,
  airComposition,
  airMassForVolumeFraction,
  mapGasComposition,
  sensibleHeatEnergy,
  splitProportionally,
  washDownEquipment,
} from './shared.js';

export type {
  AerateBatchParams,
  AerateBatchResult,
  DoseFromSiloParams,
  DoseFromSiloResult,
  FormPortionsParams,
  FormPortionsResult,
  MixBatchParams,
  MixBatchResult,
} from './mixing.js';
export {
  AERATOR_DEFINITION,
  CONTINUOUS_MIXER_DEFINITION,
  DEFAULT_BASE_DENSITY_KG_PER_M3,
  DEFAULT_MIX_SPECIFIC_HEAT_J_PER_KG_K,
  DIVIDER_DEFINITION,
  EXTRUDER_DEFINITION,
  GUILLOTINE_DEFINITION,
  PISTON_DEPOSITOR_DEFINITION,
  PLANETARY_MIXER_DEFINITION,
  ROTARY_MOULDER_DEFINITION,
  SHEETER_DEFINITION,
  SIEVE_DEFINITION,
  SIFTER_DEFINITION,
  SILO_DOSER_DEFINITION,
  SPIRAL_MIXER_DEFINITION,
  ULTRASONIC_CUTTER_DEFINITION,
  VOLUMETRIC_DEPOSITOR_DEFINITION,
  WIRE_CUT_MOULDER_DEFINITION,
  aerateBatch,
  createAerator,
  createContinuousMixer,
  createDivider,
  createExtruder,
  createGuillotine,
  createPistonDepositor,
  createPlanetaryMixer,
  createRotaryMoulder,
  createSheeter,
  createSieve,
  createSifter,
  createSiloDoser,
  createSpiralMixer,
  createUltrasonicCutter,
  createVolumetricDepositor,
  createWireCutMoulder,
  doseFromSilo,
  formPortions,
  mixBatch,
} from './mixing.js';

export type {
  ApplyFinishParams,
  ApplyFinishResult,
  EnrobeParams,
  EnrobeResult,
  HoldAtTemperatureParams,
  HoldAtTemperatureResult,
  TemperChocolateParams,
  TemperChocolateResult,
} from './finishing.js';
export {
  AIRBRUSH_DEFINITION,
  BLAST_CHILLER_DEFINITION,
  CHOCOLATE_MELT_TEMP_C,
  CHOCOLATE_SEED_TEMP_C,
  CHOCOLATE_WORK_TEMP_C,
  EDIBLE_INK_PRINTER_DEFINITION,
  ENROBER_DEFINITION,
  FREEZER_DEFINITION,
  GLAZING_DEFINITION,
  HEATING_COP,
  ICING_DEPOSITOR_DEFINITION,
  LAYERING_LINE_DEFINITION,
  PROOFER_DEFINITION,
  RETARDER_DEFINITION,
  SPIRAL_COOLER_DEFINITION,
  SPRAY_DEFINITION,
  SPRINKLE_APPLICATOR_DEFINITION,
  TEMPERING_KETTLE_DEFINITION,
  applyFinish,
  createAirbrushApplicator,
  createBlastChiller,
  createEdibleInkPrinter,
  createEnrober,
  createFreezer,
  createGlazer,
  createIcingDepositor,
  createLayeringLine,
  createProofer,
  createRetarder,
  createSprayApplicator,
  createSprinkleApplicator,
  createSpiralCooler,
  createTemperingKettle,
  enrobe,
  holdAtTemperature,
  temperChocolate,
} from './finishing.js';

export type {
  FlushModifiedAtmosphereParams,
  FlushModifiedAtmosphereResult,
  InspectAndSortParams,
  InspectAndSortResult,
  InspectionStation,
  PackageProductParams,
  PackageProductResult,
  PalletiseParams,
  PalletiseResult,
  TakeQaSampleParams,
  TakeQaSampleResult,
} from './packaging.js';
export {
  CASE_PACKER_DEFINITION,
  CHECKWEIGHER_DEFINITION,
  DATE_CODER_DEFINITION,
  FLOW_WRAPPER_DEFINITION,
  LABELLER_DEFINITION,
  MAP_FLUSH_DEFINITION,
  METAL_DETECTOR_DEFINITION,
  PALLETISER_DEFINITION,
  QA_LAB_DEFINITION,
  THERMOFORMER_DEFINITION,
  TRAY_SEALER_DEFINITION,
  VISION_INSPECTION_DEFINITION,
  XRAY_INSPECTION_DEFINITION,
  checkWeightTolerance,
  createCasePacker,
  createCheckweigher,
  createDateCoder,
  createFlowWrapper,
  createLabeller,
  createMapFlushStation,
  createMetalDetector,
  createPalletiser,
  createQaLab,
  createTraySealer,
  createThermoformer,
  createVisionInspection,
  createXrayInspection,
  flushModifiedAtmosphere,
  inspectAndSort,
  measureColour,
  measureMoisture,
  measurePh,
  measureTexture,
  measureWaterActivity,
  packageProduct,
  palletise,
} from './packaging.js';
