/**
 * Steam-tube oven: a sealed loop of saturated steam, generated by a boiler
 * and condensing inside fixed tubes that form (or heat) the baking surface,
 * with the condensate pumped back to the boiler. The steam itself never
 * contacts the product or the atmosphere — the loop is closed — so, unlike
 * `pressureSteamer.ts`, no water element mass crosses into the product zone
 * here; only conducted heat does. That closed loop is also this family's
 * real physical constraint that no other family in this directory has: the
 * tube wall can only deliver as much heat as the boiler is actually
 * generating steam to supply, a real capacity ceiling rather than an
 * unbounded electrical or gas element.
 *
 * The tube wall itself runs close to the steam's own saturation temperature
 * (see `steamPhysics.ts`), which is why steam-tube equipment is prized for a
 * *stable*, self-limiting surface temperature — steam cannot run hotter than
 * its saturation point at the boiler's operating pressure, unlike a
 * resistive electric element or a gas flame.
 */

import { CONDUCTION_COEFFICIENT_W_PER_M2_K, type OvenHeatSource } from '../oven.js';
import { saturationTempC } from './steamPhysics.js';
import { stepFamilyWithOvenSource } from './support.js';
import type { FamilyStepBase, FamilyStepResult, OvenProfile } from './types.js';

export const STEAM_TUBE_PROFILE: OvenProfile = {
  id: 'steam-tube',
  label: 'Steam-tube oven',
  mechanism:
    'Conduction from tube walls held near the saturation temperature of a closed, boiler-fed steam loop; the steam itself never contacts the product.',
  goodAt: [
    'a stable, self-limiting surface temperature (steam cannot run hotter than its own saturation point)',
    'gentle, even conductive baking without any combustion products near the product',
  ],
  badAt: [
    'high peak temperatures (bounded by the boiler’s operating pressure and the steam curve)',
    'fast throughput increases (the boiler’s own steam-generation rate caps deliverable heat)',
  ],
};

export interface SteamTubeStepParams extends FamilyStepBase {
  readonly boilerPressurePa: number;
  readonly contactAreaM2: number;
  readonly source: OvenHeatSource;
  /** The boiler's maximum continuous steam-generation capacity, expressed as
   * the heat rate it can sustain, W. A real, finite ceiling this family
   * alone enforces — no other family in this directory has an equipment
   * capacity cap independent of the requested flux. */
  readonly boilerCapacityW: number;
}

export function steamTubeStep(params: SteamTubeStepParams): FamilyStepResult {
  if (params.boilerCapacityW < 0) {
    throw new RangeError(`boilerCapacityW must not be negative, got ${params.boilerCapacityW}`);
  }
  const tubeTempC = saturationTempC(params.boilerPressurePa);
  const nominalW = CONDUCTION_COEFFICIENT_W_PER_M2_K * params.contactAreaM2 * (tubeTempC - params.surfaceTempC);
  // The boiler cannot deliver more heat than it can generate steam for; a
  // negative (heat-losing) flux is never capped, only a positive demand.
  const conductionW = nominalW > 0 ? Math.min(nominalW, params.boilerCapacityW) : nominalW;

  return stepFamilyWithOvenSource('steam-tube', { conduction: conductionW }, conductionW, params.source, params);
}
